import { Color } from '@material-ui/lab';

export default {
  prefersDarkMode: 'prefersDarkMode',
  action: 'action',
  update: 'update',
  delete: 'delete',
  refetch: 'refetch',
  default: 'default',
  sign: 'sign',
  token: 'token',
  user: 'user',
  password: 'password',
  success: <Color>'success',
  error: <Color>'error',
  info: <Color>'info',
  warning: <Color>'warning',
  app: 'app',
  all: 'all',
  indeterminate: 'indeterminate',
  redirect: 'redirect',
  home: 'home',
  layout: 'layout',
  profile: 'profile',
  book: 'book',
  books: 'books',
  getBooks: 'getBooks',
  sheikh: 'sheikh',
  sheikhs: 'sheikhs',
  getSheikhs: 'getSheikhs',
  search: 'search',
  category: 'category',
  categories: 'categories',
  getCategories: 'getCategories',
  indexView: 'indexView',
  indexes: 'indexes',
  dump: 'dump',
  type: 'type',
  content: 'content',
  contentCat: 'contentCat',
};
